services:
  - type: web
    name: lessenza-app
    env: static
    staticPublishPath: /dist
    routes:
      - type: rewrite
        source: /login
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
