services:
  - type: web
    name: lessenza
    env: static
    staticPublishPath: /dist # Ajusta según la carpeta donde están tus archivos estáticos
    routes:
      - type: rewrite
        source: /login
        destination: /index.html
      - type: rewrite
        source: /*   # Redirige todas las rutas no estáticas a index.html
        destination: /index.html
